import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{cleanup,render,screen,waitFor}from'@testing-library/react';import userEvent from'@testing-library/user-event';import{MemoryRouter}from'react-router-dom';import{afterEach,describe,expect,it,vi}from'vitest';import App from'../App';import{AuthProvider}from'../auth';import{useAuth}from'../auth-context';import{StatusBadge}from'../components/StatusBadge';
const owner={UserID:'user-1',OrganizationID:'org-1',Email:'admin@example.test',DisplayName:'Demo Owner',Roles:['OWNER']};
function json(body:unknown,status=200){return Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}))}
function renderApp(path='/'){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>)}
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe('RestoreGuard web interface',()=>{
it('logs in without storing tokens in localStorage',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>{const path=String(input);if(path.includes('/auth/session'))return json({error:{}},401);if(path.includes('/auth/login')&&init?.method==='POST')return json({user:owner});return json({})});renderApp('/login');await screen.findByRole('heading',{name:'Sign in'});await userEvent.type(screen.getByLabelText('Email'),'admin@example.test');await userEvent.type(screen.getByLabelText('Password'),'correct-horse-battery-staple');await userEvent.click(screen.getByRole('button',{name:'Sign in'}));await waitFor(()=>expect(screen.queryByRole('heading',{name:'Sign in'})).not.toBeInTheDocument());expect(localStorage.length).toBe(0)});
it('shows recovery overview dimensions and explains coverage',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).includes('/auth/session')?json({user:owner}):json({data:{protectedAssets:1,verifiedAssets:1,neverTested:0,rpoFailures:0,rtoFailures:0,failedDrills:0,inconclusiveDrills:0,runningDrills:0,recoveryCoveragePercent:100},coverageExplanation:'Verified assets divided by enabled protected assets.'}));renderApp('/');expect(await screen.findByRole('heading',{name:'Recovery Overview'})).toBeInTheDocument();expect(screen.getByText('Verified Recovery')).toBeInTheDocument();expect(await screen.findByText(/Verified assets divided/)).toBeInTheDocument()});
it('presents failed and inconclusive status with text and icon',()=>{const{rerender}=render(<StatusBadge status="FAILED"/>);expect(screen.getByText('FAILED')).toBeInTheDocument();rerender(<StatusBadge status="INCONCLUSIVE"/>);expect(screen.getByText('INCONCLUSIVE')).toBeInTheDocument()});
it('enforces permission calculation for viewers',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>json({user:{...owner,Roles:['VIEWER']}}));function Guard(){const{can}=useAuth();return <span>{can('drill.run')?'allowed':'forbidden'}</span>}render(<MemoryRouter><AuthProvider><Guard/></AuthProvider></MemoryRouter>);expect(await screen.findByText('forbidden')).toBeInTheDocument()});
});
